on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    env:
      tag: v1.0.2
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Create Executable
        run: pyinstaller --onefile client.py --name RoundnetAI_TournamentClient_${{ env.tag }} --icon img/logo.ico

      - name: Zip Necessary Files
        uses: vimtor/action-zip@v1
        with:
          files: dist/RoundnetAI_TournamentClient_${{ env.tag }}.exe Config.ini Login_Example.ini README.md notify.mp3
          dest: dist/RoundnetAI_TournamentClient_${{ env.tag }}.zip

      - name: Publish a New Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/RoundnetAI_TournamentClient_${{ env.tag }}.zip, dist/RoundnetAI_TournamentClient_${{ env.tag }}.exe
          tag: ${{ env.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}